-- Seed ~90 common system exercises (Strong-compatible naming)
-- Run after 0001_init.sql

insert into public.exercises (name, muscle_group, equipment, is_system) values
  -- Chest
  ('Bench Press (Barbell)',            'chest',     'barbell',    true),
  ('Bench Press (Dumbbell)',           'chest',     'dumbbell',   true),
  ('Incline Bench Press (Barbell)',    'chest',     'barbell',    true),
  ('Incline Bench Press (Dumbbell)',   'chest',     'dumbbell',   true),
  ('Decline Bench Press (Barbell)',    'chest',     'barbell',    true),
  ('Decline Bench Press (Dumbbell)',   'chest',     'dumbbell',   true),
  ('Chest Fly (Dumbbell)',             'chest',     'dumbbell',   true),
  ('Chest Fly (Machine)',              'chest',     'machine',    true),
  ('Cable Crossover',                  'chest',     'cable',      true),
  ('Push Up',                          'chest',     'bodyweight', true),
  ('Dip (Assisted)',                   'chest',     'machine',    true),
  ('Dip (Weighted)',                   'chest',     'bodyweight', true),
  ('Chest Press (Machine)',            'chest',     'machine',    true),

  -- Back
  ('Deadlift (Barbell)',               'back',      'barbell',    true),
  ('Romanian Deadlift (Barbell)',      'back',      'barbell',    true),
  ('Romanian Deadlift (Dumbbell)',     'back',      'dumbbell',   true),
  ('Sumo Deadlift (Barbell)',          'back',      'barbell',    true),
  ('Pull Up',                          'back',      'bodyweight', true),
  ('Pull Up (Weighted)',               'back',      'bodyweight', true),
  ('Chin Up',                          'back',      'bodyweight', true),
  ('Lat Pulldown (Cable)',             'back',      'cable',      true),
  ('Seated Row (Cable)',               'back',      'cable',      true),
  ('Seated Row (Machine)',             'back',      'machine',    true),
  ('Bent Over Row (Barbell)',          'back',      'barbell',    true),
  ('Bent Over Row (Dumbbell)',         'back',      'dumbbell',   true),
  ('T-Bar Row',                        'back',      'barbell',    true),
  ('Single Arm Row (Dumbbell)',        'back',      'dumbbell',   true),
  ('Face Pull (Cable)',                'back',      'cable',      true),
  ('Shrug (Barbell)',                  'back',      'barbell',    true),
  ('Shrug (Dumbbell)',                 'back',      'dumbbell',   true),
  ('Pullover (Dumbbell)',              'back',      'dumbbell',   true),

  -- Legs
  ('Squat (Barbell)',                  'legs',      'barbell',    true),
  ('Front Squat (Barbell)',            'legs',      'barbell',    true),
  ('Goblet Squat (Dumbbell)',          'legs',      'dumbbell',   true),
  ('Bulgarian Split Squat (Dumbbell)', 'legs',      'dumbbell',   true),
  ('Lunges (Dumbbell)',                'legs',      'dumbbell',   true),
  ('Lunges (Barbell)',                 'legs',      'barbell',    true),
  ('Walking Lunge (Dumbbell)',         'legs',      'dumbbell',   true),
  ('Leg Press (Machine)',              'legs',      'machine',    true),
  ('Leg Extension (Machine)',          'legs',      'machine',    true),
  ('Leg Curl (Machine)',               'legs',      'machine',    true),
  ('Seated Leg Curl (Machine)',        'legs',      'machine',    true),
  ('Hip Thrust (Barbell)',             'legs',      'barbell',    true),
  ('Glute Bridge (Barbell)',           'legs',      'barbell',    true),
  ('Calf Raise (Standing)',            'legs',      'machine',    true),
  ('Calf Raise (Seated)',              'legs',      'machine',    true),
  ('Hack Squat (Machine)',             'legs',      'machine',    true),
  ('Smith Machine Squat',              'legs',      'machine',    true),

  -- Shoulders
  ('Overhead Press (Barbell)',         'shoulders', 'barbell',    true),
  ('Overhead Press (Dumbbell)',        'shoulders', 'dumbbell',   true),
  ('Arnold Press (Dumbbell)',          'shoulders', 'dumbbell',   true),
  ('Lateral Raise (Dumbbell)',         'shoulders', 'dumbbell',   true),
  ('Lateral Raise (Cable)',            'shoulders', 'cable',      true),
  ('Lateral Raise (Machine)',          'shoulders', 'machine',    true),
  ('Front Raise (Dumbbell)',           'shoulders', 'dumbbell',   true),
  ('Rear Delt Fly (Dumbbell)',         'shoulders', 'dumbbell',   true),
  ('Rear Delt Fly (Machine)',          'shoulders', 'machine',    true),
  ('Upright Row (Barbell)',            'shoulders', 'barbell',    true),
  ('Upright Row (Dumbbell)',           'shoulders', 'dumbbell',   true),
  ('Shoulder Press (Machine)',         'shoulders', 'machine',    true),

  -- Biceps
  ('Bicep Curl (Barbell)',             'biceps',    'barbell',    true),
  ('Bicep Curl (Dumbbell)',            'biceps',    'dumbbell',   true),
  ('Bicep Curl (Cable)',               'biceps',    'cable',      true),
  ('Hammer Curl (Dumbbell)',           'biceps',    'dumbbell',   true),
  ('Preacher Curl (Barbell)',          'biceps',    'barbell',    true),
  ('Preacher Curl (Dumbbell)',         'biceps',    'dumbbell',   true),
  ('Concentration Curl (Dumbbell)',    'biceps',    'dumbbell',   true),
  ('Incline Curl (Dumbbell)',          'biceps',    'dumbbell',   true),
  ('EZ Bar Curl',                      'biceps',    'ez_bar',     true),

  -- Triceps
  ('Tricep Pushdown (Cable)',          'triceps',   'cable',      true),
  ('Tricep Extension (Dumbbell)',      'triceps',   'dumbbell',   true),
  ('Tricep Extension (Barbell)',       'triceps',   'barbell',    true),
  ('Skull Crusher (Barbell)',          'triceps',   'barbell',    true),
  ('Skull Crusher (EZ Bar)',           'triceps',   'ez_bar',     true),
  ('Overhead Tricep Extension (Dumbbell)', 'triceps', 'dumbbell', true),
  ('Overhead Tricep Extension (Cable)',    'triceps', 'cable',    true),
  ('Close Grip Bench Press (Barbell)', 'triceps',   'barbell',    true),
  ('Tricep Dip (Bench)',               'triceps',   'bodyweight', true),

  -- Core
  ('Plank',                            'core',      'bodyweight', true),
  ('Side Plank',                       'core',      'bodyweight', true),
  ('Crunch',                           'core',      'bodyweight', true),
  ('Sit Up',                           'core',      'bodyweight', true),
  ('Russian Twist',                    'core',      'bodyweight', true),
  ('Hanging Leg Raise',                'core',      'bodyweight', true),
  ('Hanging Knee Raise',               'core',      'bodyweight', true),
  ('Cable Crunch',                     'core',      'cable',      true),
  ('Ab Wheel Rollout',                 'core',      'other',      true),
  ('Decline Sit Up',                   'core',      'bodyweight', true),

  -- Cardio
  ('Running',                          'cardio',    'other',      true),
  ('Cycling',                          'cardio',    'machine',    true),
  ('Elliptical',                       'cardio',    'machine',    true),
  ('Rowing Machine',                   'cardio',    'machine',    true),
  ('Stair Climber',                    'cardio',    'machine',    true),
  ('Jump Rope',                        'cardio',    'other',      true),
  ('Burpees',                          'cardio',    'bodyweight', true),
  ('Incline Walking',                  'cardio',    'machine',    true);
