-- Adds ~165 more system exercises on top of 0002 for a total of ~260.
-- Strong-compatible naming. Safe to re-run (on conflict do nothing).
-- Run after 0002_seed_exercises.sql.

insert into public.exercises (name, muscle_group, equipment, is_system) values
  -- ============ Chest additions ============
  ('Landmine Press',                    'chest',     'barbell',    true),
  ('Svend Press (Plate)',               'chest',     'other',      true),
  ('Pin Press (Barbell)',               'chest',     'barbell',    true),
  ('Floor Press (Barbell)',             'chest',     'barbell',    true),
  ('Floor Press (Dumbbell)',            'chest',     'dumbbell',   true),
  ('Spoto Press (Barbell)',             'chest',     'barbell',    true),
  ('Pec Deck (Machine)',                'chest',     'machine',    true),
  ('Cable Fly (Low to High)',           'chest',     'cable',      true),
  ('Cable Fly (High to Low)',           'chest',     'cable',      true),
  ('Incline Cable Fly',                 'chest',     'cable',      true),
  ('Incline Push Up',                   'chest',     'bodyweight', true),
  ('Decline Push Up',                   'chest',     'bodyweight', true),
  ('Wide Grip Push Up',                 'chest',     'bodyweight', true),
  ('Archer Push Up',                    'chest',     'bodyweight', true),
  ('Plyometric Push Up',                'chest',     'bodyweight', true),
  ('Svend Press (Plate Squeeze)',       'chest',     'other',      true),
  ('Board Press (Barbell)',             'chest',     'barbell',    true),
  ('Close Grip Bench Press (Dumbbell)', 'chest',     'dumbbell',   true),

  -- ============ Back additions ============
  ('Deficit Deadlift (Barbell)',        'back',      'barbell',    true),
  ('Trap Bar Deadlift',                 'back',      'barbell',    true),
  ('Rack Pull (Barbell)',               'back',      'barbell',    true),
  ('Pendlay Row (Barbell)',             'back',      'barbell',    true),
  ('Yates Row (Barbell)',               'back',      'barbell',    true),
  ('Meadows Row (Barbell)',             'back',      'barbell',    true),
  ('Chest Supported Row (Dumbbell)',    'back',      'dumbbell',   true),
  ('Chest Supported Row (Machine)',     'back',      'machine',    true),
  ('Inverted Row',                      'back',      'bodyweight', true),
  ('Straight Arm Pulldown (Cable)',     'back',      'cable',      true),
  ('Kroc Row (Dumbbell)',               'back',      'dumbbell',   true),
  ('Reverse Grip Row (Barbell)',        'back',      'barbell',    true),
  ('Wide Grip Pull Up',                 'back',      'bodyweight', true),
  ('Close Grip Pull Up',                'back',      'bodyweight', true),
  ('Neutral Grip Pull Up',              'back',      'bodyweight', true),
  ('Lat Pulldown (Wide Grip)',          'back',      'cable',      true),
  ('Lat Pulldown (Close Grip)',         'back',      'cable',      true),
  ('Lat Pulldown (Reverse Grip)',       'back',      'cable',      true),
  ('Lat Pulldown (Neutral Grip)',       'back',      'cable',      true),
  ('Good Morning (Barbell)',            'back',      'barbell',    true),
  ('Hyperextension',                    'back',      'bodyweight', true),
  ('Weighted Hyperextension',           'back',      'other',      true),
  ('Reverse Hyperextension',            'back',      'machine',    true),
  ('Kettlebell Swing',                  'back',      'other',      true),
  ('Jefferson Curl (Dumbbell)',         'back',      'dumbbell',   true),
  ('Stiff Leg Deadlift (Barbell)',      'back',      'barbell',    true),
  ('Single Leg Romanian Deadlift (Dumbbell)', 'back', 'dumbbell',  true),

  -- ============ Legs additions ============
  ('Low Bar Squat (Barbell)',           'legs',      'barbell',    true),
  ('High Bar Squat (Barbell)',          'legs',      'barbell',    true),
  ('Pause Squat (Barbell)',             'legs',      'barbell',    true),
  ('Box Squat (Barbell)',               'legs',      'barbell',    true),
  ('Pin Squat (Barbell)',               'legs',      'barbell',    true),
  ('Zercher Squat (Barbell)',           'legs',      'barbell',    true),
  ('Safety Bar Squat',                  'legs',      'barbell',    true),
  ('Belt Squat',                        'legs',      'machine',    true),
  ('Split Squat (Barbell)',             'legs',      'barbell',    true),
  ('Reverse Lunge (Dumbbell)',          'legs',      'dumbbell',   true),
  ('Reverse Lunge (Barbell)',           'legs',      'barbell',    true),
  ('Side Lunge (Dumbbell)',             'legs',      'dumbbell',   true),
  ('Curtsy Lunge (Dumbbell)',           'legs',      'dumbbell',   true),
  ('Step Up (Dumbbell)',                'legs',      'dumbbell',   true),
  ('Step Up (Barbell)',                 'legs',      'barbell',    true),
  ('Box Jump',                          'legs',      'bodyweight', true),
  ('Pistol Squat',                      'legs',      'bodyweight', true),
  ('Single Leg Press (Machine)',        'legs',      'machine',    true),
  ('Nordic Curl',                       'legs',      'bodyweight', true),
  ('Glute Ham Raise',                   'legs',      'machine',    true),
  ('Sissy Squat',                       'legs',      'bodyweight', true),
  ('Sumo Squat (Dumbbell)',             'legs',      'dumbbell',   true),
  ('Cossack Squat',                     'legs',      'bodyweight', true),
  ('Single Leg Calf Raise (Dumbbell)',  'legs',      'dumbbell',   true),
  ('Donkey Calf Raise',                 'legs',      'machine',    true),
  ('Tibialis Raise',                    'legs',      'bodyweight', true),
  ('Bodyweight Squat',                  'legs',      'bodyweight', true),
  ('Jump Squat',                        'legs',      'bodyweight', true),
  ('Jumping Lunge',                     'legs',      'bodyweight', true),
  ('Wall Sit',                          'legs',      'bodyweight', true),
  ('Glute Kickback (Cable)',            'legs',      'cable',      true),
  ('Glute Kickback (Machine)',          'legs',      'machine',    true),
  ('Abduction (Machine)',               'legs',      'machine',    true),
  ('Adduction (Machine)',               'legs',      'machine',    true),
  ('Hip Abduction (Cable)',             'legs',      'cable',      true),
  ('Banded Clamshell',                  'legs',      'other',      true),

  -- ============ Shoulders additions ============
  ('Push Press (Barbell)',              'shoulders', 'barbell',    true),
  ('Push Press (Dumbbell)',             'shoulders', 'dumbbell',   true),
  ('Push Jerk (Barbell)',               'shoulders', 'barbell',    true),
  ('Bradford Press (Barbell)',          'shoulders', 'barbell',    true),
  ('Z Press (Barbell)',                 'shoulders', 'barbell',    true),
  ('Z Press (Dumbbell)',                'shoulders', 'dumbbell',   true),
  ('Cuban Press (Dumbbell)',            'shoulders', 'dumbbell',   true),
  ('Plate Front Raise',                 'shoulders', 'other',      true),
  ('Y-Raise (Dumbbell)',                'shoulders', 'dumbbell',   true),
  ('Reverse Pec Deck',                  'shoulders', 'machine',    true),
  ('Cable Rear Delt Row',               'shoulders', 'cable',      true),
  ('Handstand Push Up',                 'shoulders', 'bodyweight', true),
  ('Pike Push Up',                      'shoulders', 'bodyweight', true),
  ('Single Arm Overhead Press (Dumbbell)', 'shoulders', 'dumbbell', true),
  ('Single Arm Landmine Press',         'shoulders', 'barbell',    true),
  ('Single Arm Lateral Raise (Cable)',  'shoulders', 'cable',      true),
  ('Leaning Lateral Raise (Dumbbell)',  'shoulders', 'dumbbell',   true),
  ('Seated Lateral Raise (Dumbbell)',   'shoulders', 'dumbbell',   true),
  ('Seated Overhead Press (Dumbbell)',  'shoulders', 'dumbbell',   true),
  ('Seated Overhead Press (Barbell)',   'shoulders', 'barbell',    true),

  -- ============ Biceps additions ============
  ('Zottman Curl (Dumbbell)',           'biceps',    'dumbbell',   true),
  ('Cross Body Hammer Curl (Dumbbell)', 'biceps',    'dumbbell',   true),
  ('Spider Curl (Dumbbell)',            'biceps',    'dumbbell',   true),
  ('Spider Curl (Barbell)',             'biceps',    'barbell',    true),
  ('Drag Curl (Barbell)',               'biceps',    'barbell',    true),
  ('Reverse Curl (Barbell)',            'biceps',    'barbell',    true),
  ('Reverse Curl (Dumbbell)',           'biceps',    'dumbbell',   true),
  ('Wrist Curl (Barbell)',              'biceps',    'barbell',    true),
  ('Wrist Curl (Dumbbell)',             'biceps',    'dumbbell',   true),
  ('Reverse Wrist Curl (Barbell)',      'biceps',    'barbell',    true),
  ('Cable Hammer Curl (Rope)',          'biceps',    'cable',      true),
  ('Cable Preacher Curl',               'biceps',    'cable',      true),
  ('21s (Barbell)',                     'biceps',    'barbell',    true),
  ('Bayesian Curl (Cable)',             'biceps',    'cable',      true),
  ('Incline Hammer Curl (Dumbbell)',    'biceps',    'dumbbell',   true),
  ('Machine Curl',                      'biceps',    'machine',    true),

  -- ============ Triceps additions ============
  ('Rope Pushdown (Cable)',             'triceps',   'cable',      true),
  ('Reverse Grip Pushdown (Cable)',     'triceps',   'cable',      true),
  ('V-Bar Pushdown (Cable)',            'triceps',   'cable',      true),
  ('Single Arm Pushdown (Cable)',       'triceps',   'cable',      true),
  ('JM Press (Barbell)',                'triceps',   'barbell',    true),
  ('California Press (Dumbbell)',       'triceps',   'dumbbell',   true),
  ('Tate Press (Dumbbell)',             'triceps',   'dumbbell',   true),
  ('Single Arm Overhead Tricep Extension (Dumbbell)', 'triceps', 'dumbbell', true),
  ('Rope Overhead Tricep Extension (Cable)',          'triceps', 'cable',    true),
  ('Close Grip Push Up',                'triceps',   'bodyweight', true),
  ('Diamond Push Up',                   'triceps',   'bodyweight', true),
  ('Tricep Kickback (Dumbbell)',        'triceps',   'dumbbell',   true),
  ('Tricep Kickback (Cable)',           'triceps',   'cable',      true),

  -- ============ Core additions ============
  ('Bicycle Crunch',                    'core',      'bodyweight', true),
  ('Reverse Crunch',                    'core',      'bodyweight', true),
  ('V-Up',                              'core',      'bodyweight', true),
  ('Toe Touch',                         'core',      'bodyweight', true),
  ('Dead Bug',                          'core',      'bodyweight', true),
  ('Bird Dog',                          'core',      'bodyweight', true),
  ('Leg Lift',                          'core',      'bodyweight', true),
  ('Flutter Kick',                      'core',      'bodyweight', true),
  ('Scissor Kick',                      'core',      'bodyweight', true),
  ('Mountain Climber',                  'core',      'bodyweight', true),
  ('Pallof Press (Cable)',              'core',      'cable',      true),
  ('Woodchopper (Cable)',               'core',      'cable',      true),
  ('Landmine 180',                      'core',      'barbell',    true),
  ('Suitcase Carry (Dumbbell)',         'core',      'dumbbell',   true),
  ('Farmer Walk (Dumbbell)',            'core',      'dumbbell',   true),
  ('Side Bend (Dumbbell)',              'core',      'dumbbell',   true),
  ('Oblique Crunch',                    'core',      'bodyweight', true),
  ('Hollow Hold',                       'core',      'bodyweight', true),
  ('L-Sit',                             'core',      'bodyweight', true),
  ('Dragon Flag',                       'core',      'bodyweight', true),
  ('Toes to Bar',                       'core',      'bodyweight', true),
  ('Knees to Elbows',                   'core',      'bodyweight', true),
  ('Windshield Wiper',                  'core',      'bodyweight', true),
  ('Weighted Crunch (Cable)',           'core',      'cable',      true),
  ('Weighted Sit Up',                   'core',      'other',      true),
  ('Copenhagen Plank',                  'core',      'bodyweight', true),

  -- ============ Cardio / Conditioning additions ============
  ('Treadmill',                         'cardio',    'machine',    true),
  ('Air Bike (Assault Bike)',           'cardio',    'machine',    true),
  ('Sled Push',                         'cardio',    'other',      true),
  ('Sled Pull',                         'cardio',    'other',      true),
  ('Battle Ropes',                      'cardio',    'other',      true),
  ('Skipping',                          'cardio',    'bodyweight', true),
  ('Shadow Boxing',                     'cardio',    'bodyweight', true),
  ('Swim',                              'cardio',    'other',      true),
  ('Walking',                           'cardio',    'other',      true),
  ('Hiking',                            'cardio',    'other',      true),

  -- ============ Forearms (new muscle group) ============
  ('Dead Hang',                         'forearms',  'bodyweight', true),
  ('Plate Pinch',                       'forearms',  'other',      true),
  ('Towel Pull Up',                     'forearms',  'bodyweight', true),
  ('Reverse Wrist Curl (Dumbbell)',     'forearms',  'dumbbell',   true),
  ('Behind the Back Wrist Curl (Barbell)', 'forearms', 'barbell',  true)

on conflict do nothing;
